version: '3.5'
services:
  telegram-api-server:
    container_name: telegram-api-server
    restart: always
    ports:
      - "9503:9503"
    volumes:
      - ./:/app-host-link
      - ./sessions:/app/sessions
    working_dir: /app-host-link
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "2"

